#!/usr/bin/env python

import sys, subprocess, os.path, tempfile, os, shutil

quantcomp = os.path.dirname(sys.argv[0]) + '/quantcomp'
compress  = '-c' in sys.argv or '--compress' in sys.argv

if compress:
    print "Running Quantiser"
    subprocess.check_call([quantcomp] + sys.argv[1:])

    print "Running bzip2"
    out, tmp = tempfile.mkstemp()
    subprocess.check_call(['bzip2', '-c', sys.argv[-1]], stdout=out)

    shutil.move(tmp, sys.argv[-1])

else:
    print "Running bzip2"
    out, tmp = tempfile.mkstemp()
    subprocess.check_call(['bunzip2', '-c', sys.argv[-2]], stdout=out)

    print "Running Dequantiser"
    args = [quantcomp] + sys.argv[1:]
    args[-2] = tmp
    subprocess.check_call(args)

    os.remove(tmp)
